name: CodeAnt Test Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # 請根據您的專案需求調整 Python 版本
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests and generate coverage
        id: generate-test-coverage
        run: |
          coverage run -m pytest tests/
          coverage xml -o coverage.xml

      - name: Fetch upload script
        env:
          API_BASE: https://ved6vc7dkvz3veaigrllnasa4y0kmqbw.lambda-url.ap-south-1.on.aws
        run: |
          curl -sS -X GET "${API_BASE}/pr/analysis/coverage/script/get" \
            --output upload_coverage.sh

      - name: Make script executable
        run: chmod +x upload_coverage.sh

      - name: Upload coverage and set status
        env:
          # 重要: 您必須在 GitHub Repo 設定中建立一個名為 ACCESS_TOKEN 的 Secret
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPO_NAME:    ${{ github.repository }}
          COMMIT_ID:    ${{ github.sha }}
        run: |
          bash upload_coverage.sh \
            -t "$ACCESS_TOKEN" \
            -r "$REPO_NAME" \
            -c "$COMMIT_ID" \
            -f coverage.xml \
            -p github \
            -m "your_module_name" # 重要: 請將此處替換為您的模組/專案名稱
