- name: Run tests and generate coverage
    id: generate-test-coverage
    run: |
      source .venv/bin/activate
      uv pip install coverage pytest
      coverage run -m pytest tests/
      coverage xml -o coverage.xml
      cat coverage.xml

  - name: Fetch upload script
    env:
      API_BASE: https://ved6vc7dkvz3veaigrllnasa4y0kmqbw.lambda-url.ap-south-1.on.aws
    run: |
      curl -sS -X GET "${API_BASE}/pr/analysis/coverage/script/get" \
        --output upload_coverage.sh

  - name: Make script executable
    run: chmod +x upload_coverage.sh

  - name: Upload coverage and set status
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REPO_NAME:    ${{ github.repository }}
      COMMIT_ID:    ${{ github.sha }}
    run: |
      bash upload_coverage.sh \
        -t "$ACCESS_TOKEN" \
        -r "$REPO_NAME" \
        -c "$COMMIT_ID" \
        -f coverage.xml \
        -p github \
        -m <module_name>
